### ISSUE TITLE
[Audio] Wrong audio file played during profile creation

### ISSUE THREAD

**Issue by HamzaChioua** [vgwb/Antura_darija#13]
The audio files with Id : Profile_Gender (are you a boy or a girl ?) are inverted during profile creation.

It plays the feminine form when a "Boy" profile is chosen , and vice versa.

**Comment by StefanoCecere** [comment]
but it doesn't play any audio clicking on the M or F images.. there is just the spoken question...

**Comment by HamzaChioua** [comment]
sorry wrong previous description . 

The wrong audio file is "select a face..." : the bug doesn't happen all the time, and I can't understand the exact pattern to reproduce. Here is what I found :

scenario 1 : 
-click "+" to create profile
-select "Boy"
-->correct file played
-click "back"
-click "+" to create profile
-select "Boy"
-->correct file played
...etc

scenario 2 : 
-click "+" to create profile
-select "Boy"
-->correct file played
-click "back"
-click "+" to create profile
-select "Girl"
-->wrong file played
-click "back"
-click "+" to create profile
-select "Boy"
-->wrong file played
...etc
