### ISSUE TITLE
[BalloonsAndNumbers] Wrong number displayed in the square 

### ISSUE THREAD

**Issue by HamzaChioua** [vgwb/Antura_darija#14]
![sc](https://user-images.githubusercontent.com/18099842/64633194-a7aa1a00-d3f2-11e9-8859-bba6b9d31117.jpg)
The number displayed in the white square (1) is not corresponding to what is written under the balloons (two). 
Is it the desired gameplay ?

**Comment by FrancyCavallari** [comment]
It seems that Balloons_counting is using the words starting from 1 while the numbers start from 0. That's why we have a bug!
Both should start from 0.
![image](https://user-images.githubusercontent.com/17926293/66118627-2b60bc00-e5d7-11e9-8b12-3ec61b479b22.png)

**Comment by CatmanIta** [comment]
Yes, we had the same bug on Antura English.
