### ISSUE TITLE
[Content] shaddah + other diacritic placement

### ISSUE THREAD

**Issue by HamzaChioua** [vgwb/Antura_darija#15]
When the shaddah is used in a letter , the other diacrititic sign must be above it (with exception of kasrah, which is always below the letter).

This is currently not the case (see screenshots)
![Screenshot_20190911-104623_Antura](https://user-images.githubusercontent.com/18099842/64687041-a4aa3a80-d481-11e9-9cbe-9bb9f5ff4e1b.jpg)
![Screenshot_20190911-104632_Antura](https://user-images.githubusercontent.com/18099842/64687052-ab38b200-d481-11e9-98d8-a2f90200d634.jpg)

**Comment by StefanoCecere** [comment]
thsi is quite complicate. the shaddah has a fixed height, while the diacritic is dynamic.
currently we can't say to the shaddah to stay below the top diacritic sign of a letter :(
