### ISSUE TITLE
[Loading Screen] Should we change it?

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_darija#5]
We could modify it to have Hamza studio and VGWB presenting...
... and the Casablanca Foundation sponsoring

**Comment by HamzaChioua** [comment]
> We could modify it to have Hamza studio and VGWB presenting...
> ... and the Casablanca Foundation sponsoring

Yes, I will provide the logos ASAP

**Comment by FrancyCavallari** [comment]
https://drive.google.com/open?id=1rTJj_Tgbz5uJUXu-6O0OmHiK9P67tvMz
Splash_screen 800x280

**Comment by FrancyCavallari** [comment]
I created the new loading screens... 
![image](https://user-images.githubusercontent.com/17926293/59920029-7cceac00-9429-11e9-80c3-b656ac3382ec.png)

![image](https://user-images.githubusercontent.com/17926293/59920039-848e5080-9429-11e9-8174-8a5b845a93af.png)

... but since for the Darija version we won't show the game logo in the loading... so I'd recommend to rename the fines we are currently using:
```
splash_screen_companies.png
splash_screen_logoantura.png

```
to simpler names:
```
splash_screen_1.png
splash_screen_2.png

```
@StefanoCecere what do you think?

**Comment by FrancyCavallari** [comment]
I pushed the new loading screens so that you can use them.
